---
version: 2.0
build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-c'
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-26/ee-supported-rhel9:latest'
  EE_BUILDER_IMAGE: 'registry.redhat.io/ansible-automation-platform-26/ansible-builder-rhel9:latest'

dependencies:
  galaxy: requirement.yml
  system: bindep.txt
  python: requirement.txt
