---
version: 3
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-26/ee-minimal-rhel9:latest

dependencies:
    system:
      - python3-pip [platform:rpm]
      - python3-pip [platform:dpkg]
      - gcc
      - python3-devel
      - openldap-devel
    python:
      - python-ldap==3.4
