download_url: https://rhel9-workstation02.mainak.com/api/galaxy/v3/plugin/ansible/content/published/collections/artifacts/ansible-netcommon-8.5.2.tar.gz
format_version: 1.0.0
name: netcommon
namespace: ansible
server: https://rhel9-workstation02.mainak.com/api/galaxy/
signatures: []
version: 8.5.2
version_url: /api/galaxy/v3/plugin/ansible/content/published/collections/index/ansible/netcommon/versions/8.5.2/
