---
# tasks file for check_patch
- name: Checking if new patch available
  hosts: localhost
  become: true
  tasks:
    - name: Load users data if stored as raw file
      ansible.builtin.set_fact:
        package_list: "{{ lookup('file', 'packages.yml') | from_yaml }}"
    - name: Checking
      ansible.builtin.shell: "dnf check-update {{ item.package }}*"
      register: update
      loop: "{{ package_list }}"
      failed_when: false

    - name: Printing
      ansible.builtin.debug:
        msg: "Package: {{ item.item.package }} | Return Code: {{ item.rc }} | Output: {{ item.stdout }}"
      loop: "{{ update.results }}"

