---
- name: Show Mount Points
  hosts: all
  tasks:
    - name: Create File
      file:
        path: /etc/demo-fstab
        state: touch
    - name: Mount Points
      copy:
        content: "{{ VOLUME_NAME }}/{{ MOUNT_PATH }}/{{ FILESYSTEM }}"
        dest: /etc/demo-fstab
